index:
  title: フナイログ
  description: The logs of a software engineer whose name is Funai.
author:
  name: Ryota Ikezawa
links:
  github: https://github.com/paveg/blog-next-contentlayer
  instagram: https://www.instagram.com/funa1y
  twitter: https://twitter.com/paveg_
