index:
  title: フナイログ
  description:
author:
  name: Ryota Ikezawa
links:
  github: https://github.com/paveg/blog-next-contentlayer
  instagram: https://www.instagram.com/funa1y
  twitter: https://twitter.com/paveg_
